name: domainbert
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21
  - pandas>=1.3
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - seaborn>=0.11
  - pytorch>=1.12
  - torchvision
  - torchaudio
  - anndata>=0.8
  - scanpy>=1.8
  - umap-learn>=0.5
  - jupyter
  - ipykernel
  - pip
  - pip:
      - transformers>=4.20
      - datasets>=2.0
      - accelerate>=0.12